// This file is automatically generated and overwritten by Capacitor
// when you run `npx cap sync android` / `npx cap copy android`.
// It is included here as a placeholder so the app runs even before the
// first sync (the WebView will simply not have the native bridge yet).
console.log('Capacitor bridge placeholder loaded - run "npx cap sync android" to install the real bridge.');
